services:
  - type: web
    name: stic
    env: node
    buildCommand: |
      npm install
      npm run db:push
      npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: stic-db
          property: connectionString
databases:
  - name: stic-db
    plan: free
